### ISSUE TITLE
Violation of view model guidelines

### ISSUE THREAD

**Issue by mkriteja** [mitchtabian/Bound-Services-with-MVVM#1]
Don’t let ViewModels (and Presenters) know about Android framework classes

please see: 
https://medium.com/androiddevelopers/viewmodels-and-livedata-patterns-antipatterns-21efaef74a54

Also see this: 
https://github.com/googlesamples/android-architecture-components/issues/20

**Comment by mitchtabian** [comment]
I was unaware of this recommendation. Thank you for the information.
